### PR TITLE
add pre-commit configs

### PR DESCRIPTION
**Pull request by luca-medeiros**
- added pre-commit configs on a followup from previous PR #83 
- added related docs
- ran the pre-commit on all files of main

### CODE REVIEW

**Comment by luca-medeiros** [comment]
Ive just seen the works of #91. @mithun2003 mind doing some review here?

**Comment by mithun2003** [comment]
Is this pre-commit check for print statements in the code beneficial? It ensures that prints are reviewed before committing changes.

**Comment by luca-medeiros** [comment]
@mithun2003 seems there are only two print statements in this repo. Not sure print reviews are needed.

**Comment by igorbenav** [comment]
Maybe we should remove the print statements at once and use proper logging for the worker, checking whether there are print statements would be useful in this case.

By the way, how do you guys feel about moving the worker script from `app` to `core/utils`?

**Comment by luca-medeiros** [comment]
Agree with the proper logging. What about creating a worker folder under `core`?
app/worker.py -> app/core/worker/settings.py, app/core/worker/functions.py

That much depth maybe too much and redundant for now, but I believe there is room for expansion for arq worker.

**Comment by igorbenav** [comment]
Yeah, I think it's a good approach. Stuff like dynamic prioritization, scheduling, custom retry would be cool.

**Comment by luca-medeiros** [comment]
Yeah, lots can be done with workers.

@igorbenav any thoughts about the PR? I though about creating a separate part on readme to further explain pre-commit to the people who fork the repo. For now, I only added an extra step to the Contributing part.

**Comment by igorbenav** [comment]
I think it's a good idea, @luca-medeiros. Do you want to add it to this PR or do it in the future? I'll merge it.

**Comment by luca-medeiros** [comment]
@igorbenav refactored the contributing docs.

**Pull request merged**
