### PR TITLE
Refactor datetime.utcnow() to datetime.now(timezone.utc)

### PR DESCRIPTION
**Pull request by mithun2003**
Updated datetime.utcnow() to datetime.now(timezone.utc) in multiple modules and added timezone.utc

Solve this issue:
https://github.com/igorbenav/FastAPI-boilerplate/issues/79

### CODE REVIEW

**Review by igorbenav — CHANGES_REQUESTED** [review]
## 1. Tests are not passing
I'm getting:
```
error = DataError("invalid input for query argument $1: datetime.datetime(2023, 12, 17, 1, 57, 1... (can't subtract offset-naive and offset-aware datetimes)")
````
Probably because of access token stuff, adding datetime.now + expires_delta.

Also:
```
asyncpg.exceptions.DataError: invalid input for query argument $1: datetime.datetime(2023, 12, 17, 1, 57, 1... (can't subtract offset-naive and offset-aware datetimes)
```
You need to handle saving timestamp aware datetime in db. This would be done adding `timezone=True` to the column definition in the sqlalchemy model, like this:
```
created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
```

## 2. Imports update
You may change all `timezone.utc` uses, like:
```
from datetime import timezone
...

current_timestamp = int(datetime.now(timezone.utc).timestamp())
```

With `UTC`, like this:
```
from datetime import UTC
...

current_timestamp = int(datetime.now(UTC).timestamp())
```

This way is simpler and works as of python 3.11

**Comment by mithun2003** [comment]
Solve all the mentioned bugs and change timezone.utc to UTC

**Review by igorbenav — CHANGES_REQUESTED** [review]
Tests still not passing.
I think the only part that is not working now is, in all model definitions, change this:

```python
updated_at: Mapped[Optional[datetime]] = mapped_column(default=None)
deleted_at: Mapped[Optional[datetime]] = mapped_column(default=None)
```

With

```python
updated_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), default=None)
deleted_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), default=None)
```

To create the columns as timestamp-aware. With the way things are now, they are create as timestamp-naive.

Try running the tests define in docker-compose.yml

**Comment by mithun2003** [comment]
I solve that issue too and do the testing. And pass all the test cases
Screenshot 2023-12-27 124000

**Review by igorbenav — APPROVED** [review]

**Comment by igorbenav** [comment]
Nice one, @mithun2003, thanks for the contribution!🚀

**Pull request merged**
